# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('UserId', models.CharField(max_length=250)),
                ('Link', models.CharField(max_length=1000)),
                ('UserPhoto', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trolls.UserLocation'),
        ),
    ]
