# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trolls', '0003_auto_20171220_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='UserCity',
            field=models.CharField(default='SOME STRING', max_length=1000),
        ),
    ]
