# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trolls', '0004_userinfo_usercity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLocation',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='UserLink',
            new_name='Link',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='UserName',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='UserCity',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='Location',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
    ]
