# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trolls', '0007_userinfo_useremail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='UserLink',
            new_name='UserBookName',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='UserPhoto',
            new_name='UserBookPrice',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='UserId',
            new_name='UserNumber',
        ),
    ]
