# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trolls', '0008_auto_20180117_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='UserBookLogo',
            field=models.FileField(default='Null', upload_to=''),
        ),
    ]
