# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trolls', '0009_userinfo_userbooklogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='UserBookLogo',
            field=models.FileField(upload_to=''),
        ),
    ]
