# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trolls', '0010_auto_20180118_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='UserNumber',
            new_name='UserPhoneNumber',
        ),
    ]
