# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Trolls', '0014_auto_20180121_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
