# Generated by Django 2.0.1 on 2018-02-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trolls', '0015_userinfo_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PdfName', models.CharField(max_length=500)),
                ('PdfBookLogo', models.FileField(upload_to='')),
                ('PdfFile', models.FileField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
