# Generated by Django 2.0.1 on 2018-02-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trolls', '0016_pdfinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PdfInfo',
        ),
    ]
