# Generated by Django 2.0.6 on 2018-07-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trolls', '0017_delete_pdfinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='UserBookName',
            field=models.CharField(max_length=10000),
        ),
    ]
