# Generated by Django 2.0.6 on 2018-07-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trolls', '0018_auto_20180729_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='UserBookName',
            field=models.CharField(max_length=1000),
        ),
    ]
