# Generated by Django 2.0.6 on 2018-07-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trolls', '0019_auto_20180729_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='Discription',
            field=models.CharField(default=2, max_length=10000),
            preserve_default=False,
        ),
    ]
