# Generated by Django 2.0.6 on 2018-07-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trolls', '0020_userinfo_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='UserPhoneNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
