# Generated by Django 2.0.6 on 2018-07-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebooks', '0002_auto_20180708_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfinfo',
            name='PdfBookLogo',
            field=models.FileField(default='SOME STRING', max_length=10000, upload_to=''),
        ),
        migrations.AddField(
            model_name='pdfinfo',
            name='PdfFile',
            field=models.FileField(default='SOME STRING', max_length=10000, upload_to=''),
        ),
        migrations.AddField(
            model_name='pdfinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
