# Generated by Django 2.0.6 on 2018-07-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebooks', '0003_auto_20180708_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
