# Generated by Django 2.0.6 on 2018-07-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebooks', '0004_auto_20180708_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfinfo',
            name='PdfBookLogo',
            field=models.FileField(max_length=10000, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pdfinfo',
            name='PdfFile',
            field=models.FileField(max_length=10000, upload_to=''),
        ),
    ]
