# Generated by Django 2.0.6 on 2018-07-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebooks', '0005_auto_20180708_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfinfo',
            name='PdfPrice',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
