# Generated by Django 2.0.6 on 2018-07-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebooks', '0007_auto_20180729_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfinfo',
            name='PdfDescription',
            field=models.CharField(default=2, max_length=10000),
            preserve_default=False,
        ),
    ]
