# Generated by Django 2.0.6 on 2018-07-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebooks', '0008_pdfinfo_pdfdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfinfo',
            name='PdfEmail',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdfinfo',
            name='PdfPhoneNumber',
            field=models.CharField(default=5, max_length=10000),
            preserve_default=False,
        ),
    ]
