# Generated by Django 2.0.6 on 2018-07-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebooks', '0009_auto_20180729_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfinfo',
            name='PdfPhoneNumber',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
